In [2]:
import numpy as np
import cv2

In [3]:
im = cv2.imread("s.png")
img = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)

In [7]:
from matplotlib import pyplot as plt

In [3]:
%matplotlib qt

In [7]:
plt.imshow(img)

In [5]:
edge = cv2.Sobel(img, cv2.CV_8U, 1, 0, ksize=3)

In [6]:
blur = cv2.blur(edge, (5, 5))

In [23]:
plt.imshow(blur)

In [7]:
thres_val, thres = cv2.threshold(blur, 0, 255, cv2.THRESH_OTSU+cv2.THRESH_BINARY)

In [32]:
plt.imshow(thres)

In [8]:
ele = cv2.getStructuringElement(cv2.MORPH_RECT, (15, 3))
morphed = cv2.morphologyEx(thres, cv2.MORPH_CLOSE, ele)

In [43]:
plt.imshow(morphed)

In [39]:
plt.imshow(thres)

In [44]:
plt.imshow(morphed-thres)

In [7]:
t = 30*25*60
vd = cv2.VideoCapture("1.mp4")

In [10]:
vd.set(1, t - 60)
img2 = cv2.cvtColor(vd.read()[1], cv2.COLOR_BGR2GRAY)
plt.imshow(img2)

In [11]:
edge2 = cv2.Sobel(img2, cv2.CV_8U, 1, 0, ksize=3)
plt.imshow(edge2)

In [12]:
blur2 = cv2.blur(edge2, (5, 5))

In [50]:
plt.imshow(blur2)

In [13]:
thres_val2, thres2 = cv2.threshold(blur2, 0, 255, cv2.THRESH_OTSU+cv2.THRESH_BINARY)

In [52]:
plt.imshow(thres2)

In [14]:
ele2 = cv2.getStructuringElement(cv2.MORPH_RECT, (15, 10))
morph = cv2.morphologyEx(thres2, cv2.MORPH_CLOSE, ele2)

In [56]:
plt.imshow(morph)

In [15]:
cnt = cv2.findContours(morph, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

In [59]:
cnt

(array([[255, 255, 255, ...,   0,   0,   0],
        [255, 255, 255, ...,   0,   0,   0],
        [255, 255, 255, ...,   0,   0,   0],
        ...,
        [255, 255, 255, ...,   0,   0,   0],
        [255, 255, 255, ...,   0,   0,   0],
        [255, 255, 255, ...,   0,   0,   0]], dtype=uint8),
 [array([[[257, 647]],
  
         [[256, 648]],
  
         [[257, 649]],
  
         [[258, 649]],
  
         [[258, 648]]], dtype=int32), array([[[573, 624]],
  
         [[573, 625]],
  
         [[573, 626]],
  
         [[573, 627]],
  
         [[574, 628]],
  
         [[574, 629]],
  
         [[575, 630]],
  
         [[575, 631]],
  
         [[576, 632]],
  
         [[576, 633]],
  
         [[576, 634]],
  
         [[577, 635]],
  
         [[577, 636]],
  
         [[577, 637]],
  
         [[577, 638]],
  
         [[577, 639]],
  
         [[577, 640]],
  
         [[577, 641]],
  
         [[577, 642]],
  
         [[577, 643]],
  
         [[577, 644]],
  
         [[577, 

In [16]:
plt.imshow(morph)

In [24]:
(thres2 == 255).sum() + (thres2 == 0).sum()

921600

In [25]:
1280*720

921600

In [27]:
l, r = 25*30*60, 35*30*60
vd.set(1, l)
data = []

while l <= r:
    suc, fr = vd.read()
    fr = cv2.resize(fr, (500, 500))
    fr = cv2.cvtColor(fr, cv2.COLOR_BGR2GRAY)
    ed = cv2.Sobel(fr, cv2.CV_8U, 1, 0, ksize=3)
    bl = cv2.blur(ed, (5, 5))
    th_val, th = cv2.threshold(bl, 0, 255, cv2.THRESH_OTSU+cv2.THRESH_BINARY)
    data.append({
        "fr" : l,
        "val" : (th==255).sum()
    })
    l += 1
    
data.sort(lambda ob : ob["val"])

TypeError: must use keyword argument for key function

In [30]:
data.sort(key = lambda o : o["val"])

In [31]:
data[:10]

[{'fr': 60281, 'val': 1974},
 {'fr': 60288, 'val': 1975},
 {'fr': 60280, 'val': 1976},
 {'fr': 60279, 'val': 1979},
 {'fr': 60276, 'val': 1990},
 {'fr': 60277, 'val': 1997},
 {'fr': 60308, 'val': 1999},
 {'fr': 60278, 'val': 2001},
 {'fr': 60312, 'val': 2003},
 {'fr': 60293, 'val': 2009}]

In [9]:
vd.set(1, 60300)
fr = vd.read()[1]
fr = cv2.cvtColor(fr, cv2.COLOR_BGR2GRAY)
ed = cv2.Sobel(fr, cv2.CV_8U, 1, 0, ksize=3)
bl = cv2.blur(ed, (5, 5))
th_val, th = cv2.threshold(bl, 0, 255, cv2.THRESH_OTSU+cv2.THRESH_BINARY)
el= cv2.getStructuringElement(cv2.MORPH_RECT, (15, 10))
morph = cv2.morphologyEx(th, cv2.MORPH_CLOSE, el)
plt.imshow(morph)

In [36]:
f= cv2.resize(fr, (2000, 2000))

In [37]:
plt.imshow(f)

In [1]:
morph

NameError: name 'morph' is not defined

In [5]:
vid2 = cv2.VideoCapture("m2.mkv")
vid2.set(1, 10*60*30)

True

In [12]:
l, r = 5*25*60, 12*25*60
vid2.set(1, l)
data = []

while l <= r:
    suc, fr = vid2.read()
    fr = cv2.resize(fr, (500, 500))
    fr = cv2.cvtColor(fr, cv2.COLOR_BGR2GRAY)
    ed = cv2.Sobel(fr, cv2.CV_8U, 1, 0, ksize=3)
    bl = cv2.blur(ed, (5, 5))
    th_val, th = cv2.threshold(bl, 0, 255, cv2.THRESH_OTSU+cv2.THRESH_BINARY)
    data.append({
        "fr" : l,
        "val" : (th==255).sum()
    })
    l += 1
    
data.sort(key = lambda ob : ob["val"])

In [124]:
print(cv2.threshold.__doc__)

threshold(src, thresh, maxval, type[, dst]) -> retval, dst
.   @brief Applies a fixed-level threshold to each array element.
.   
.   The function applies fixed-level thresholding to a multiple-channel array. The function is typically
.   used to get a bi-level (binary) image out of a grayscale image ( cv::compare could be also used for
.   this purpose) or for removing a noise, that is, filtering out pixels with too small or too large
.   values. There are several types of thresholding supported by the function. They are determined by
.   type parameter.
.   
.   Also, the special values cv::THRESH_OTSU or cv::THRESH_TRIANGLE may be combined with one of the
.   above values. In these cases, the function determines the optimal threshold value using the Otsu's
.   or Triangle algorithm and uses it instead of the specified thresh . The function returns the
.   computed threshold value. Currently, the Otsu's and Triangle methods are implemented only for 8-bit
.   images.
.   
.   @note In

In [8]:
vid2.set(1, 12907)
fr = vid2.read()[1]
fr = cv2.cvtColor(fr, cv2.COLOR_BGR2GRAY)
fr = cv2.resize(fr, (500, 500))
ed = cv2.Sobel(fr, cv2.CV_8U, 1, 0, ksize=3)
bl = cv2.blur(ed, (5, 5))
th_val, th = cv2.threshold(bl, 0, 255, cv2.THRESH_OTSU+cv2.THRESH_BINARY)
el= cv2.getStructuringElement(cv2.MORPH_RECT, (15, 10))
morph = cv2.morphologyEx(th, cv2.MORPH_CLOSE, el)
plt.imshow(morph)

In [22]:
plt.imshow(fr)

In [9]:
contour = cv2.findContours(morph, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
len(contour)

3

In [25]:
print(cv2.findContours.__doc__)

findContours(image, mode, method[, contours[, hierarchy[, offset]]]) -> image, contours, hierarchy
.   @brief Finds contours in a binary image.
.   
.   The function retrieves contours from the binary image using the algorithm @cite Suzuki85 . The contours
.   are a useful tool for shape analysis and object detection and recognition. See squares.cpp in the
.   OpenCV sample directory.
.   @note Since opencv 3.2 source image is not modified by this function.
.   
.   @param image Source, an 8-bit single-channel image. Non-zero pixels are treated as 1's. Zero
.   pixels remain 0's, so the image is treated as binary . You can use cv::compare, cv::inRange, cv::threshold ,
.   cv::adaptiveThreshold, cv::Canny, and others to create a binary image out of a grayscale or color one.
.   If mode equals to cv::RETR_CCOMP or cv::RETR_FLOODFILL, the input can also be a 32-bit integer image of labels (CV_32SC1).
.   @param contours Detected contours. Each contour is stored as a vector of points (e.g.

In [10]:
cntr, hier = contour[1:]

In [11]:
d = []
for c in cntr:
    rect = cv2.minAreaRect(c)
    d.append(rect)

In [13]:
d

[((119.0, 479.5), (3.0, 2.0), -90.0),
 ((269.5911865234375, 465.47021484375),
  (67.19340515136719, 7.012625217437744),
  -88.12212371826172),
 ((281.4410705566406, 417.8078918457031),
  (3.8327479362487793, 22.071338653564453),
  -7.594642639160156),
 ((45.0, 393.5), (3.0, 2.0), -90.0),
 ((309.5, 385.0), (7.0, 24.0), -0.0),
 ((273.5, 377.0), (5.0, 28.0), -0.0),
 ((236.5, 302.5), (1.0, 1.0), -90.0),
 ((274.2689514160156, 307.6484069824219),
  (8.520034790039062, 95.29415130615234),
  -3.1108405590057373),
 ((211.0, 244.0), (10.0, 4.0), -90.0),
 ((265.66595458984375, 238.4889678955078),
  (8.048799514770508, 29.53443717956543),
  -3.8140745162963867),
 ((219.81558227539062, 200.02870178222656),
  (37.93447494506836, 13.942503929138184),
  -84.80557250976562),
 ((249.525390625, 186.9813690185547),
  (9.433813095092773, 41.931182861328125),
  -9.727578163146973),
 ((268.5, 155.0), (5.0, 14.0), -0.0),
 ((262.3577575683594, 103.9949722290039),
  (90.55106353759766, 19.292343139648438),
  -8

In [151]:
plt.imshow(fr)

In [71]:
vid2.set(1, 12880)

True

In [72]:
fr2=vid2.read()[1]
fr2= cv2.cvtColor(fr2, cv2.COLOR_BGR2GRAY)

In [83]:
fr2 = cv2.resize(fr2, (500, 500))
ed = cv2.Sobel(fr2, cv2.CV_8U, 1, 0, ksize=3)
bl = cv2.blur(ed, (5, 5))
th_val, th2 = cv2.threshold(bl, 0, 255, cv2.THRESH_OTSU+cv2.THRESH_BINARY)
el= cv2.getStructuringElement(cv2.MORPH_RECT, (15, 10))
morph2 = cv2.morphologyEx(th, cv2.MORPH_CLOSE, el)

In [91]:
plt.imshow(fr2)

In [31]:
box = cv2.boxPoints(d[0])

SystemError: new style getargs format but argument is not a tuple

In [26]:
box = np.int0(box)

In [29]:
x=cv2.drawContours(morph, [box], 0, (0, 0, 255), 2)

In [30]:
plt.imshow(x)

In [36]:
b=[]
for rec in d:
    box = cv2.boxPoints(rec)
    box = np.int0(box)
    b.append(box)

cv2.drawContours(fr, b, -1, (0, 0, 255), 2)
plt.imshow(fr)

In [45]:
cv2.drawContours(fr, b, 0, (0, 0, 255), 2)
plt.imshow(fr)

In [46]:
plt.imshow(fr)

In [47]:
vid2.set(1, 12907)
fr = vid2.read()[1]
fr = cv2.cvtColor(fr, cv2.COLOR_BGR2GRAY)
fr = cv2.resize(fr, (500, 500))

In [673]:
qq=fr.copy()
cv2.drawContours(qq, b, 14, (0, 0, 255), 2)
plt.imshow(qq)

error: C:\bld\opencv_1506447021968\work\opencv-3.3.0\modules\imgproc\src\drawing.cpp:2495: error: (-215) 0 <= contourIdx && contourIdx < (int)last in function cv::drawContours


## 

In [65]:
d[14]

((124.5, 39.5), (89.0, 25.0), -0.0)

In [87]:
b[14]

array([[ 80,  52],
       [ 80,  27],
       [169,  27],
       [169,  52]], dtype=int64)

In [106]:
plt.imshow(qq[27:52, 80:169])

In [98]:
b[14][2][0]

169

In [99]:
area = []
aspra = []
for bx in b:
    w, h = np.abs(bx[0][0] - bx[2][0]), np.abs(bx[2][1] - bx[0][1])
    print((w, h))
    aspra.append(w/h)
    area.append(w * h)

(2, 3)
(4, 68)
(0, 23)
(2, 3)
(7, 24)
(5, 28)
(1, 1)
(3, 96)
(4, 10)
(6, 30)
(11, 39)
(2, 43)
(5, 14)
(8, 93)
(89, 25)


In [101]:
aspra

[0.6666666666666666,
 0.058823529411764705,
 0.0,
 0.6666666666666666,
 0.2916666666666667,
 0.17857142857142858,
 1.0,
 0.03125,
 0.4,
 0.2,
 0.28205128205128205,
 0.046511627906976744,
 0.35714285714285715,
 0.08602150537634409,
 3.56]

In [104]:
aspra.index(max(aspra))

14

In [563]:
el= cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
tophat = cv2.morphologyEx(qq[27:52, 80:169].copy(), cv2.MORPH_BLACKHAT, el)
plt.imshow(tophat)

In [220]:
ocr = cv2.imread("ocr-b.png")
ocr = cv2.cvtColor(ocr, cv2.COLOR_BGR2GRAY)

In [177]:
plt.imshow(ocr)

In [221]:
ocr = cv2.threshold(ocr, 0, 255, cv2.THRESH_OTSU+cv2.THRESH_BINARY)[1]

In [222]:
_, cnt, __ = cv2.findContours(ocr.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

In [226]:
rects = []
for i in range(0, 10):
    rects.append(cv2.minAreaRect(cnt[i]))

In [229]:
rt = ocr.copy()
cv2.drawContours(rt, b, -1, (128, 255, 0), 2)
plt.imshow(rt)

In [227]:
b=[]
for rec in rects:
    box = cv2.boxPoints(rec)
    box = np.int0(box)
    b.append(box)

In [228]:
rects

[((872.5, 89.0), (132.0, 87.0), -90.0),
 ((756.0, 89.5), (88.0, 133.0), -0.0),
 ((641.0, 89.5), (74.0, 133.0), -0.0),
 ((537.396728515625, 89.18415832519531),
  (122.25184631347656, 84.70816040039062),
  -65.0952377319336),
 ((410.0, 89.5), (133.0, 84.0), -90.0),
 ((169.5, 89.0), (51.0, 132.0), -0.0),
 ((1105.9815673828125, 86.38671112060547),
  (89.1290512084961, 131.59332275390625),
  -9.246112823486328),
 ((987.0, 88.5), (88.0, 135.0), -0.0),
 ((293.17913818359375, 88.3129653930664),
  (134.9610137939453, 78.33386993408203),
  -88.81881713867188),
 ((63.0, 88.5), (88.0, 135.0), -0.0)]

In [247]:
kk = cnt.copy()
rr = rects.copy()

In [300]:
z = zip(kk, rr)
(c, r) = zip(*sorted(z, key = lambda o: o[1][0][0]))

In [301]:
c

(array([[[ 65,  21]],
 
        [[ 64,  22]],
 
        [[ 50,  22]],
 
        [[ 49,  23]],
 
        [[ 45,  23]],
 
        [[ 44,  24]],
 
        [[ 41,  24]],
 
        [[ 40,  25]],
 
        [[ 39,  25]],
 
        [[ 38,  26]],
 
        [[ 37,  26]],
 
        [[ 36,  27]],
 
        [[ 35,  27]],
 
        [[ 29,  33]],
 
        [[ 29,  34]],
 
        [[ 27,  36]],
 
        [[ 27,  37]],
 
        [[ 26,  38]],
 
        [[ 26,  40]],
 
        [[ 25,  41]],
 
        [[ 25,  43]],
 
        [[ 24,  44]],
 
        [[ 24,  47]],
 
        [[ 23,  48]],
 
        [[ 23,  51]],
 
        [[ 22,  52]],
 
        [[ 22,  56]],
 
        [[ 21,  57]],
 
        [[ 21,  64]],
 
        [[ 20,  65]],
 
        [[ 20,  84]],
 
        [[ 19,  85]],
 
        [[ 19,  93]],
 
        [[ 20,  94]],
 
        [[ 20, 111]],
 
        [[ 21, 112]],
 
        [[ 21, 119]],
 
        [[ 22, 120]],
 
        [[ 22, 125]],
 
        [[ 23, 126]],
 
        [[ 23, 129]],
 
        [[ 24, 1

In [271]:
l.sort(key = lambda o: o[1][0][0])

In [315]:
rt = ocr.copy()
cv2.drawContours(rt, c, 9, (128, 255, 0), 2)
plt.imshow(rt)

In [318]:
dig = [0]*10
for (i, ct) in enumerate(c):
    (x, y, w, h) = cv2.boundingRect(ct)
    roi = ocr[y:y+h, x:x+w]
    roi = cv2.resize(roi, (57, 88))
    dig[i] = roi

In [319]:
dig

[array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([[  0,   0,   0, ..., 255, 255, 255],
        [  0,   0,   0, ..., 255, 255, 255],
        [  0,   0,   0, ..., 255, 255, 255],
        ...,
        [  0,   0,   0, ..., 255, 255, 255],
        [  0,   0,   0, ..., 255, 255, 255],
        [  0,   0,   0, ..., 255, 230,  65]], dtype=uint8),
 array([[  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        ...,
        [ 54, 255, 255, ..., 255, 161,   0],
        [ 53, 255, 255, ..., 255, 161,   0],
        [ 54, 255, 255, ..., 255,  43,   0]], dtype=uint8),
 array([[255, 255, 255, ...,   0,   0,   0],
        [255, 255, 255, ...,   0,   0,   0],
        [255, 255, 255, ...,   0,   0,   0],
        ...,
        [  0,   0,   0, ...,  

In [538]:
sqKernel = cv2.getStructuringElement(cv2.MORPH_RECT, (1, 5))

In [539]:
# gradX = cv2.Sobel(tophat, ddepth=cv2.CV_32F, dx=1, dy=0, ksize=-1)
# gradX = np.absolute(gradX)
# (minVal, maxVal) = (np.min(gradX), np.max(gradX))
# gradX = (255 * ((gradX - minVal) / (maxVal - minVal)))
# gradX = gradX.astype("uint8")

In [658]:
gradX = tophat.copy()
el = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 4))
gradX = cv2.morphologyEx(gradX, cv2.MORPH_CLOSE, el)
thresh = cv2.threshold(gradX, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)[1]

In [659]:
cnts1 = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
cnts1 = cnts1[1]
locs = []

In [684]:
rt = tophat.copy()
cv2.drawContours(rt, cnts1, -1, (128, 255, 0), 2)

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0, 128],
       [  0,   0,   0, ...,   0, 128, 128],
       ...,
       [  0,   0,   0, ...,   0, 128, 128],
       [  0,   0, 128, ..., 128, 128, 128],
       [  0, 128, 128, ..., 128, 128, 128]], dtype=uint8)

In [685]:
len(cnts1)

25

In [686]:
plt.imshow(rt)

In [678]:
plt.imshow(thresh)

In [669]:
for (i, c) in enumerate(cnts1):
    locs.append(cv2.boundingRect(c))
locs = sorted(locs, key=lambda x:x[0])

In [680]:
cnts1 = cv2.findContours(tophat.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
cnts1 = cnts1[1]
locs = []

In [731]:
vid2.set(1, 12887)
fr2 = vid2.read()[1]
fr2 = cv2.cvtColor(fr2, cv2.COLOR_BGR2GRAY)
fr2 = cv2.resize(fr2, (500, 500))
el= cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
blht = cv2.morphologyEx(fr2[27:52, 80:169].copy(), cv2.MORPH_TOPHAT, el)
plt.imshow(blht)

In [701]:
tpht = cv2.morphologyEx(fr2[27:52, 80:169].copy(), cv2.MORPH_TOPHAT, el)
plt.imshow(tpht)

In [803]:
vid2.set(1, 12927)
fr3 = vid2.read()[1]
fr3 = cv2.cvtColor(fr3, cv2.COLOR_BGR2GRAY)
fr3 = cv2.resize(fr3, (500, 500))
# el= cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
# blht = cv2.morphologyEx(fr3[27:52, 80:169].copy(), cv2.MORPH_TOPHAT, el)

vid2.set(1, 12957)
fr2 = vid2.read()[1]
fr2 = cv2.cvtColor(fr2, cv2.COLOR_BGR2GRAY)
fr2 = cv2.resize(fr2, (500, 500))
# el= cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
# blht2 = cv2.morphologyEx(fr2[27:52, 80:169].copy(), cv2.MORPH_TOPHAT, el)
# plt.imshow(blht2)

In [765]:
frfr = blht - blht2

In [787]:
plt.imshow(blht)

In [788]:
plt.imshow(blht2)

In [786]:
plt.imshow(frfr)

In [806]:
plt.imshow((fr2-fr3)[27:52, 80:169])